trigger:

- master

pool:
  vmImage: 'windows-latest'
  
steps:
- script: |
    call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
    pushd src
    call NMake.exe
  displayName: 'Running NMAKE'