trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: |
    pushd src
    nuget.exe restore
  displayName: 'Restoring packages with nuget'

- script: |
    pushd src
    "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\msbuild.exe" "BuildXL Installer.sln" /m /p:Configuration=Debug /p:Platform=x64 /nologo
  displayName: 'Building with MSBuild'
