trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'src/BuildXL Install.sln'
    feedsToUse: 'select'
  displayName: 'Restoring packages with nuget'

- task: MSBuild@1
  inputs:
    solution: 'src\BuildXL Installer.sln'
    msbuildArchitecture: 'x64'
    platform: 'x64'
    configuration: 'Debug'
    maximumCpuCount: true
  displayName: 'Building with MSBuild'