trigger:

- master

pool:
  vmImage: 'windows-latest'
  
steps:
- script: |
    call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Auxiliary\\Build\\vcvars64.bat"
    pushd src
    call NMake.exe
  displayName: 'Running NMAKE'
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)\s\src\BuildXL.Setup\bin\x64\Debug\BuildXL.Setup.msi'
    artifact: 'BuildXL Installer MSI'
    publishLocation: 'pipeline'
  displayName: 'Publishing compiled installer (MSI)'