name: MSBuild and WiX

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Nuget restore
      run: pushd src && nuget restore
    - name: Run MSBuild
      run: pushd src && msbuild "BuildXL Installer.sln" /m
